# Building and publishing Docker containers via Gitlab CI/CD
# Author: Jordan A Caraballo-Vega, jordan.a.caraballo-vega@nasa.gov

variables:
  CONTAINER_NAME: "slump-detection-cuda11.1" # container name, e.g. mycontainer
  CONTAINER_VERSION: "latest" # container version, e.g. 1.0.0

stages:
  - build
  - build_singularity

build_slump-detection:
  stage: build
  tags:
    - build
    - push
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/requirements/Dockerfile 
      --destination $CI_REGISTRY/$CI_PROJECT_PATH/$CONTAINER_NAME:$CONTAINER_VERSION
    only:
      changes:
      - requirements/Dockerfile

build_slump-detection-singularity:
  stage: build_singularity
  tags:
    - singularity
  script: 
    - cd requirements; singularity build ${CONTAINER_NAME}.sif Singularity.def
    - >
       singularity push --docker-username "${CI_REGISTRY_USER}" --docker-password "${CI_REGISTRY_PASSWORD}" 
       ${CONTAINER_NAME}.sif oras://$CI_REGISTRY/$CI_PROJECT_PATH/${CONTAINER_NAME}:${CONTAINER_VERSION}
    - ls -lth ${CONTAINER_NAME}.sif
  #only:
  #  changes:
  #  - base/cisto-data-science/*
  #  #- .gitlab-ci.yml
