variables:
  CONTAINER_NAME: "$CI_PROJECT_NAME-container" # container name, e.g. mycontainer
  CONFIGURATION_LOCATION: "$CI_PROJECT_DIR/Dockerfile" # container configuration, e.g. packages/Dockerfile
  CONTAINER_VERSION: "latest" # container version, e.g. 1.0.0

# Build ILAB Datascience Container
build_singularity_container:
  stage: build
  tags:
    - build
    - push
    - singularity
  image: 
    name: gitlab.nccs.nasa.gov:5050/nccs-ci/nccs-containers/singularity/nccs-centos7-singularity37:latest
    entrypoint: [""]
  allow_failure: false
  dependencies: []
  script: 
    - singularity build ${CONTAINER_NAME}.sif $CONFIGURATION_LOCATION
    - >
       singularity push --docker-username "${CI_REGISTRY_USER}" --docker-password "${CI_REGISTRY_PASSWORD}" 
       ${CONTAINER_NAME}.sif oras://$CI_REGISTRY/$CI_PROJECT_PATH/$CONTAINER_NAME:$CONTAINER_VERSION
